import type { Idea } from './types';

const now = Date.now();
const d = (days: number, hours = 0) => now - days * 86400000 - hours * 3600000;
const f = (days: number) => now + days * 86400000;

let _id = 1;
const id = () => _id++;

const rawSeed: Omit<Idea, 'sketches'>[] = [
  {
    id: id(),
    title: 'Campus laundry tracker — live machine map',
    body: "Dorm machines are always taken at the worst time. A tiny live map of which washers are free, plus a text when mine finishes.\n\nCould scrape the existing pay portal instead of adding hardware.",
    tags: ['hackathon', 'side-project'],
    project: 'Side Projects',
    due: f(5),
    archived: false,
    createdAt: d(1),
    extras: { checklist: true, sketch: true },
    checklist: [
      { text: 'Sketch the 3 core screens', done: true },
      { text: 'Check if the laundry portal has an API', done: false, today: true },
      { text: "Ask 5 floormates if they'd use it", done: false },
    ],
    links: [],
  },
  {
    id: id(),
    title: 'Thesis angle: coastal insurance redlining',
    body: "Follow the money, not just the water — where insurers pull out might predict displacement better than flood maps.",
    tags: ['essay', 'research'],
    project: 'Senior Thesis',
    due: f(2),
    archived: false,
    createdAt: d(1, 19),
    extras: { checklist: true, links: true },
    checklist: [
      { text: 'Find 2 datasets on policy withdrawal', done: false },
      { text: 'Email Prof. Anand for a reading list', done: false, today: true },
    ],
    links: [{ label: 'NOAA flood policy dataset' }],
  },
  {
    id: id(),
    title: 'Auto-build flashcards from lecture markdown',
    body: '',
    tags: ['cs', 'study'],
    project: 'CS 301',
    due: f(9),
    archived: false,
    createdAt: d(2),
    extras: { checklist: true },
    checklist: [
      { text: 'Pick a parser', done: true },
      { text: 'Wire up a review schedule', done: false },
    ],
    links: [],
  },
  {
    id: id(),
    title: 'Photo series for the portfolio review',
    body: '',
    tags: ['creative'],
    project: 'Personal',
    due: null,
    archived: false,
    createdAt: d(3),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Study-group scheduling poll that respects sleep',
    body: '',
    tags: ['study'],
    project: null,
    due: null,
    archived: false,
    createdAt: d(3),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Reading notes — Jane Jacobs, ch. 3',
    body: 'Sidewalks as infrastructure. The "eyes on the street" idea maps onto digital community moderation surprisingly well.',
    tags: ['research', 'essay'],
    project: 'Senior Thesis',
    due: null,
    archived: false,
    createdAt: d(4),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Pomodoro timer that soft-blocks Discord',
    body: '',
    tags: ['side-project', 'cs'],
    project: null,
    due: null,
    archived: false,
    createdAt: d(5),
    extras: { checklist: true },
    checklist: [
      { text: 'Decide: browser extension vs menubar app', done: false },
    ],
    links: [],
  },
  {
    id: id(),
    title: 'Grant idea: low-cost soil sensors for the campus garden',
    body: '',
    tags: ['research', 'hackathon'],
    project: null,
    due: null,
    archived: false,
    createdAt: d(6),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Refactor the portfolio site to be fully static',
    body: '',
    tags: ['cs', 'creative'],
    project: 'Personal',
    due: null,
    archived: false,
    createdAt: d(8),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Essay intro — three hook options to test',
    body: "1. Open on the closed gas station.\n2. Open on the insurance letter.\n3. Open on the high-water mark on the wall.",
    tags: ['essay'],
    project: 'Senior Thesis',
    due: null,
    archived: false,
    createdAt: d(9),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Questions to bring to office hours',
    body: '',
    tags: ['research'],
    project: null,
    due: null,
    archived: false,
    createdAt: d(11),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Shared grocery list app for the apartment',
    body: '',
    tags: ['side-project'],
    project: 'Side Projects',
    due: null,
    archived: false,
    createdAt: d(12),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Lecture demo: visualize sorting algorithms',
    body: '',
    tags: ['cs', 'study'],
    project: 'CS 301',
    due: null,
    archived: false,
    createdAt: d(14),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Spring break: dig through the regional archive',
    body: '',
    tags: ['research'],
    project: 'Senior Thesis',
    due: null,
    archived: false,
    createdAt: d(16),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Logo sketches for the hack team',
    body: '',
    tags: ['creative', 'hackathon'],
    project: null,
    due: null,
    archived: false,
    createdAt: d(19),
    extras: {},
    checklist: [],
    links: [],
  },
  {
    id: id(),
    title: 'Read up on retrieval practice vs re-reading',
    body: '',
    tags: ['study'],
    project: null,
    due: null,
    archived: false,
    createdAt: d(21),
    extras: {},
    checklist: [],
    links: [],
  },
];

export const seedIdeas: Idea[] = rawSeed.map(i => ({ ...i, sketches: [] }));
